export const SITE_NAME = 'Nội Thất Duy Mạnh'
export const SITE_DESCRIPTION = 'Xưởng sản xuất và thi công tủ bếp, nội thất gia đình tại Vân Nam - Phúc Thọ - Hà Nội'

export const CONTACT = {
  hotline: '094.872.8091',
  hotlineRaw: '0948728091',
  address: 'Vân Nam - Phúc Thọ - Hà Nội',
  workHours: '8h00 - 18h00',
  zaloUrl: process.env.NEXT_PUBLIC_ZALO_URL || 'https://zalo.me/0948728091',
  facebookUrl: process.env.NEXT_PUBLIC_FACEBOOK_URL || 'https://facebook.com/duymanhnoithat',
  email: 'duymanhnoithat@gmail.com',
  mapsEmbedUrl: '',
} as const

export const NAV_LINKS = [
  { label: 'Trang Chủ', href: '/' },
  { label: 'Giới Thiệu', href: '/gioi-thieu' },
  { label: 'Tủ Bếp', href: '/tu-bep' },
  { label: 'Nội Thất Khác', href: '/noi-that-khac' },
  { label: 'Dự Án Thực Tế', href: '/du-an-thuc-te' },
  { label: 'Video Công Trình', href: '/video-cong-trinh' },
  { label: 'Tin Tức', href: '/tin-tuc' },
  { label: 'Liên Hệ', href: '/lien-he' },
  { label: 'Báo Giá', href: '/bao-gia' },
] as const

export const BOTTOM_NAV_ITEMS = [
  { label: 'Trang Chủ', href: '/', icon: 'Home' },
  { label: 'Tủ Bếp', href: '/tu-bep', icon: 'LayoutGrid' },
  { label: 'Báo Giá', href: '/bao-gia', icon: 'FileText', cta: true },
  { label: 'Dự Án', href: '/du-an-thuc-te', icon: 'Building2' },
  { label: 'Thêm', href: '#more', icon: 'Menu' },
] as const

export const BOTTOM_NAV_MORE_LINKS = [
  { label: 'Giới Thiệu', href: '/gioi-thieu', icon: 'Info' },
  { label: 'Nội Thất Khác', href: '/noi-that-khac', icon: 'Sofa' },
  { label: 'Video Công Trình', href: '/video-cong-trinh', icon: 'Video' },
  { label: 'Tin Tức', href: '/tin-tuc', icon: 'Newspaper' },
  { label: 'Liên Hệ', href: '/lien-he', icon: 'Phone' },
  { label: 'Đánh Giá KH', href: '/danh-gia-khach-hang', icon: 'Star' },
] as const

export const ADMIN_NAV_ITEMS = [
  { label: 'Dashboard', href: '/admin/dashboard', icon: 'LayoutDashboard' },
  { label: 'Form Yêu Cầu', href: '/admin/forms', icon: 'FileText' },
  { label: 'Sản Phẩm', href: '/admin/products', icon: 'Package' },
  { label: 'Danh Mục SP', href: '/admin/categories', icon: 'Tag' },
  { label: 'Dự Án', href: '/admin/projects', icon: 'Building2' },
  { label: 'Video', href: '/admin/videos', icon: 'Video' },
  { label: 'Tin Tức', href: '/admin/news', icon: 'Newspaper' },
  { label: 'Bảng Giá', href: '/admin/pricing', icon: 'DollarSign' },
  { label: 'Đánh Giá', href: '/admin/reviews', icon: 'Star' },
  { label: 'Trang Chủ', href: '/admin/pages', icon: 'LayoutTemplate' },
  { label: 'Phân Tích', href: '/admin/analytics', icon: 'BarChart2' },
  { label: 'System Log', href: '/admin/logs', icon: 'ScrollText' },
  { label: 'Cài Đặt', href: '/admin/settings', icon: 'Settings' },
  { label: 'Người Dùng', href: '/admin/users', icon: 'Users' },
] as const

export const PRODUCT_CATEGORIES = [
  { label: 'Tủ Bếp Inox 304', slug: 'tu-bep-inox-304', href: '/tu-bep/tu-bep-inox-304' },
  { label: 'Tủ Bếp Cánh Kính', slug: 'tu-bep-canh-kinh', href: '/tu-bep/tu-bep-canh-kinh' },
  { label: 'Tủ Bếp Acrylic', slug: 'tu-bep-acrylic', href: '/tu-bep/tu-bep-acrylic' },
  { label: 'Tủ Quần Áo', slug: 'tu-quan-ao', href: '/noi-that-khac/tu-quan-ao' },
  { label: 'Vách Tivi', slug: 'vach-tivi', href: '/noi-that-khac/vach-tivi' },
  { label: 'Nội Thất Phòng Ngủ', slug: 'noi-that-phong-ngu', href: '/noi-that-khac/noi-that-phong-ngu' },
] as const

// 63 tỉnh/thành phố trực thuộc TW của Việt Nam
export const PROVINCES = [
  { label: 'Tất Cả', value: '' },
  // 5 thành phố trực thuộc TW
  { label: 'Hà Nội', value: 'Hà Nội' },
  { label: 'TP. Hồ Chí Minh', value: 'TP. Hồ Chí Minh' },
  { label: 'Hải Phòng', value: 'Hải Phòng' },
  { label: 'Đà Nẵng', value: 'Đà Nẵng' },
  { label: 'Cần Thơ', value: 'Cần Thơ' },
  // 58 tỉnh — sắp xếp theo bảng chữ cái
  { label: 'An Giang', value: 'An Giang' },
  { label: 'Bà Rịa - Vũng Tàu', value: 'Bà Rịa - Vũng Tàu' },
  { label: 'Bắc Giang', value: 'Bắc Giang' },
  { label: 'Bắc Kạn', value: 'Bắc Kạn' },
  { label: 'Bạc Liêu', value: 'Bạc Liêu' },
  { label: 'Bắc Ninh', value: 'Bắc Ninh' },
  { label: 'Bến Tre', value: 'Bến Tre' },
  { label: 'Bình Định', value: 'Bình Định' },
  { label: 'Bình Dương', value: 'Bình Dương' },
  { label: 'Bình Phước', value: 'Bình Phước' },
  { label: 'Bình Thuận', value: 'Bình Thuận' },
  { label: 'Cà Mau', value: 'Cà Mau' },
  { label: 'Cao Bằng', value: 'Cao Bằng' },
  { label: 'Đắk Lắk', value: 'Đắk Lắk' },
  { label: 'Đắk Nông', value: 'Đắk Nông' },
  { label: 'Điện Biên', value: 'Điện Biên' },
  { label: 'Đồng Nai', value: 'Đồng Nai' },
  { label: 'Đồng Tháp', value: 'Đồng Tháp' },
  { label: 'Gia Lai', value: 'Gia Lai' },
  { label: 'Hà Giang', value: 'Hà Giang' },
  { label: 'Hà Nam', value: 'Hà Nam' },
  { label: 'Hà Tĩnh', value: 'Hà Tĩnh' },
  { label: 'Hải Dương', value: 'Hải Dương' },
  { label: 'Hậu Giang', value: 'Hậu Giang' },
  { label: 'Hòa Bình', value: 'Hòa Bình' },
  { label: 'Hưng Yên', value: 'Hưng Yên' },
  { label: 'Khánh Hòa', value: 'Khánh Hòa' },
  { label: 'Kiên Giang', value: 'Kiên Giang' },
  { label: 'Kon Tum', value: 'Kon Tum' },
  { label: 'Lai Châu', value: 'Lai Châu' },
  { label: 'Lâm Đồng', value: 'Lâm Đồng' },
  { label: 'Lạng Sơn', value: 'Lạng Sơn' },
  { label: 'Lào Cai', value: 'Lào Cai' },
  { label: 'Long An', value: 'Long An' },
  { label: 'Nam Định', value: 'Nam Định' },
  { label: 'Nghệ An', value: 'Nghệ An' },
  { label: 'Ninh Bình', value: 'Ninh Bình' },
  { label: 'Ninh Thuận', value: 'Ninh Thuận' },
  { label: 'Phú Thọ', value: 'Phú Thọ' },
  { label: 'Phú Yên', value: 'Phú Yên' },
  { label: 'Quảng Bình', value: 'Quảng Bình' },
  { label: 'Quảng Nam', value: 'Quảng Nam' },
  { label: 'Quảng Ngãi', value: 'Quảng Ngãi' },
  { label: 'Quảng Ninh', value: 'Quảng Ninh' },
  { label: 'Quảng Trị', value: 'Quảng Trị' },
  { label: 'Sóc Trăng', value: 'Sóc Trăng' },
  { label: 'Sơn La', value: 'Sơn La' },
  { label: 'Tây Ninh', value: 'Tây Ninh' },
  { label: 'Thái Bình', value: 'Thái Bình' },
  { label: 'Thái Nguyên', value: 'Thái Nguyên' },
  { label: 'Thanh Hóa', value: 'Thanh Hóa' },
  { label: 'Thừa Thiên Huế', value: 'Thừa Thiên Huế' },
  { label: 'Tiền Giang', value: 'Tiền Giang' },
  { label: 'Trà Vinh', value: 'Trà Vinh' },
  { label: 'Tuyên Quang', value: 'Tuyên Quang' },
  { label: 'Vĩnh Long', value: 'Vĩnh Long' },
  { label: 'Vĩnh Phúc', value: 'Vĩnh Phúc' },
  { label: 'Yên Bái', value: 'Yên Bái' },
] as const
